# killchain.yml
kill_chain:
  name: "PrinterC2 - lolc2 NSFW Campaign"
  version: "1.2"
  description: >
    Full-spectrum offensive simulation leveraging multi-stage payloads, 
    signed binaries, fallback drivers, data destruction, and automated deployment.
    Cross-platform with Windows/macOS support and integrated post-exploitation logic.
  platform: 
    - Windows
    - macOS
    - Networked Printers
  deployment_mode: automated
  automation:
    orchestrator: "Custom Red Team Pipeline"
    schedule: "event-triggered or operator-driven"
    deployment_engine: 
      - "PowerShell"
      - "HTA"
      - "Custom Dropper Chain"
    command_control:
      - "PrinterC2 over HTTPS"
      - "AnyDesk RAT fallback"

  stages:

    - stage: Initial Access
      techniques:
        - id: T1190
          name: Exploit Public-Facing Application
          tactic: initial-access
          details: >
            Network printer compromise via spooler service overflow.
        - id: T1566.001
          name: Phishing: Spearphishing Attachment
          tactic: initial-access
          details: >
            Payload hidden in `nsfw.jpg`, `nsfw.pdf`, or `nsfw.png` using stego + certutil.

    - stage: Execution
      techniques:
        - id: T1059.001
          name: Command and Scripting Interpreter: PowerShell
          tactic: execution
          details: >
            `dropper.ps1` invokes staging and execution of payload chain.
        - id: T1218.005
          name: Signed Binary Proxy Execution: Mshta
          tactic: defense-evasion
          details: >
            Executes `popup.hta` for dynamic memory-based `encryptor.exe` delivery.

    - stage: Persistence
      techniques:
        - id: T1547.001
          name: Boot or Logon Autostart Execution: Registry Run Keys
          tactic: persistence
          details: >
            `register_keys.ps1` inserts run keys to maintain loader persistence.
        - id: T1546.015
          name: Event Triggered Execution: Component Object Model Hijacking
          tactic: persistence
          details: >
            Optional COM persistence via `builder.exe`.
        - id: T1525
          name: Implant Internal Image or Driver
          tactic: persistence
          details: >
            `print32.dll` used as fallback LOLOBYOL persistence implant.

    - stage: Privilege Escalation
      techniques:
        - id: T1068
          name: Exploitation for Privilege Escalation
          tactic: privilege-escalation
          details: >
            `HiveNightmare.exe` targets SYSTEM credential hives on vulnerable endpoints.
        - id: T1548.002
          name: Abuse Elevation Control Mechanism: Bypass UAC
          tactic: privilege-escalation
          details: >
            Used in `loader.ps1` with elevated token impersonation.

    - stage: Defense Evasion
      techniques:
        - id: T1216
          name: Signed Binary Proxy Execution
          tactic: defense-evasion
          details: >
            `AnyDesk` RAT used for stealthy cross-platform remote access.
        - id: T1211
          name: Exploitation of Remote Services
          tactic: lateral-movement
          details: >
            `print32.dll` dropped via shared print queue services as BYOL technique.

    - stage: Credential Access
      techniques:
        - id: T1003.001
          name: OS Credential Dumping: LSASS Memory
          tactic: credential-access
          details: >
            Memory dump logic within HiveNightmare and PowerShell tokens.
        - id: T1003.004
          name: OS Credential Dumping: LSA Secrets
          tactic: credential-access
          details: >
            Secrets extraction via SYSTEM hive elevation.

    - stage: Discovery
      techniques:
        - id: T1083
          name: File and Directory Discovery
          tactic: discovery
          details: >
            Droppers scan for files related to backups or password managers.
        - id: T1518.001
          name: Security Software Discovery: Security Tools
          tactic: discovery
          details: >
            Identifies AV/EPP tools to choose driverless fallback or signed exec.

    - stage: Lateral Movement
      techniques:
        - id: T1021.002
          name: Remote Services: SMB/Windows Admin Shares
          tactic: lateral-movement
          details: >
            Spread loader using print queue misconfigs and admin shares.

    - stage: Command and Control
      techniques:
        - id: T1071.001
          name: Application Layer Protocol: Web Protocols
          tactic: command-and-control
          details: >
            C2 over HTTP(S) embedded in image uploads via PrinterC2 custom traffic.
        - id: T1105
          name: Ingress Tool Transfer
          tactic: command-and-control
          details: >
            Transfers `encryptor.exe`, `popup.hta`, and `loobims` via C2 channels.
        - id: T1219
          name: Remote Access Software
          tactic: command-and-control
          details: >
            AnyDesk used for remote ops with signed binary benefits.

    - stage: Exfiltration
      techniques:
        - id: T1041
          name: Exfiltration Over C2 Channel
          tactic: exfiltration
          details: >
            Files encoded and exfiltrated via AnyDesk tunnel or disguised web traffic.
        - id: T1020
          name: Automated Exfiltration
          tactic: exfiltration
          details: >
            Configured to exfil after `dcryptor.exe` execution.

    - stage: Impact
      techniques:
        - id: T1485
          name: Data Destruction
          tactic: impact
          details: >
            `encryptor.exe` optionally invokes `dcryptor.exe` for permanent deletion.
        - id: T1491.001
          name: Internal Defacement
          tactic: impact
          details: >
            `popup.hta` launched to deliver ransom-style visual or misinformation.
  
  artifacts:
    - name: "README.md"
      type: documentation
      purpose: Campaign breakdown and IOCs.
    - name: "PrinterC2_Chain.exe"
      type: compiled binary
      purpose: Builder + persistent key + loader payload.
    - name: "print32.dll"
      type: dll
      purpose: Embedded loldriver/backdoor access.
    - name: "HiveNightmare.exe"
      type: binary
      purpose: SYSTEM hive access and local token scraping.
    - name: "popup.hta"
      type: HTA script
      purpose: Used for ransomware simulation/defacement.
    - name: "loobims"
      type: macOS binary
      purpose: Covert C2 channel for Apple systems.
    - name: "encryptor.exe"
      type: wiper/encryptor
      purpose: Targeted data destruction.
    - name: "nsfw.*"
      type: staged payload
      purpose: Image/document based delivery vector.

  automation_hooks:
    - trigger: "initial-infection"
      script: "dropper.ps1"
    - trigger: "post-exploitation"
      script: "register_keys.ps1"
    - trigger: "data-theft"
      binary: "HiveNightmare.exe"
    - trigger: "impact"
      binary: "encryptor.exe"
    - trigger: "defacement"
      launcher: "popup.hta"

